# Generated by Django 3.2.1 on 2021-05-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usersID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
