# Generated by Django 3.2.1 on 2021-05-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210530_0751'),
        ('users', '0014_user_usersid'),
    ]

    operations = [
    ]
