# Generated by Django 3.2.1 on 2021-05-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_0002_auto_20210530_0751_0014_user_usersid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_1',
        ),
    ]
